creds = Program.first.google_app_credentials
ENV['GOOGLE_ACCOUNT_TYPE'] ||= creds['GOOGLE_ACCOUNT_TYPE']
ENV['GOOGLE_PRIVATE_KEY_ID'] ||= creds['GOOGLE_PRIVATE_KEY_ID']
ENV['GOOGLE_PRIVATE_KEY'] ||= creds['GOOGLE_PRIVATE_KEY']
ENV['GOOGLE_CLIENT_EMAIL'] ||= creds['GOOGLE_CLIENT_EMAIL']
ENV['GOOGLE_CLIENT_ID'] ||= creds['GOOGLE_CLIENT_ID']
ENV['GOOGLE_SUB_EMAIL'] ||= creds['GOOGLE_SUB_EMAIL']