development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true

test: *development

staging: 
  url: <%= ENV['REDIS_URL'] %>
  timeout: 1

production: 
  url: <%= ENV['REDIS_URL'] %>
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>
  timeout: 1