octopus:
  environments:
    - development
    - staging
    - production

  development:
    program_shards:
      web: 
        adapter:  postgresql
        host:     localhost
        database: compass_development

      web_2:
        adapter:  postgresql
        host:     localhost
        database: compass_development

  staging:
    program_shards:
      web:
        adapter:  postgresql
        host:     localhost
        encoding: unicode
        database: web_staging
      pt:
        adapter:  postgresql
        host:     localhost
        encoding: unicode
        database: pt_staging

  production:
    program_shards:
      web:
        adapter: postgresql
        user: <%= ENV['WEB_DATABASE_USER'] %>
        password: <%= ENV['WEB_DATABASE_PASSWORD'] %>
        encoding: unicode
        host: <%= ENV['WEB_DATABASE_HOST'] %>
        database: <%= ENV['WEB_DATABASE_NAME'] %>
        pool: 10
